### ISSUE TITLE
[Bug]: ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

### ISSUE THREAD

**Issue by shanmugamani1023** [open-edge-platform/anomalib#1934]
### Describe the bug

i cant install anomalib,(anamolib) PS D:\Shravtek\neutech_airfillter\anamolib\anomalib> anomalib install 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shan\.conda\envs\anamolib\Scripts\anomalib.exe\__main__.py", line 4, in <module>
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\__init__.py", line 6, in <module>
    from .cli import AnomalibCLI
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\cli.py", line 19, in <module>
    from anomalib.cli.utils.help_formatter import CustomHelpFormatter, get_short_docstring
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\utils\__init__.py", line 6, in <module>
    from .help_formatter import CustomHelpFormatter
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\utils\help_formatter.py", line 26, in <module>
    from anomalib.engine import Engine
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\engine\__init__.py", line 6, in <module>
    from .engine import Engine
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\engine\engine.py", line 20, in <module>
    from anomalib.callbacks.checkpoint import ModelCheckpoint
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\callbacks\__init__.py", line 18, in <module>
    from .model_loader import LoadModelCallback
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\callbacks\model_loader.py", line 12, in <module>
    from anomalib.models.components import AnomalyModule
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\__init__.py", line 13, in <module>
    from anomalib.models.components import AnomalyModule
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\__init__.py", line 8, in <module>
    from .feature_extractors import TimmFeatureExtractor, TorchFXFeatureExtractor
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\feature_extractors\__init__.py", line 6, in <module>
    from .timm import TimmFeatureExtractor
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\feature_extractors\timm.py", line 12, in <module>
    import timm
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

### Dataset

MVTec

### Model

PADiM

### Steps to reproduce the behavior

![error](https://github.com/openvinotoolkit/anomalib/assets/119931738/26adda3c-da5d-453a-8c84-14fdf818f34d)

### OS information

OS information:
- OS: [e.g. windows 10]
- Python version: [e.g. 3.11]
- Anomalib version: 1.1.0 dev0

### Expected behavior

need to instal

### Pip/GitHub

pip

### Configuration YAML

```yaml
null
```

### Logs

```shell
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\shan\.conda\envs\anamolib\Scripts\anomalib.exe\__main__.py", line 4, in <module>
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\__init__.py", line 6, in <module>
    from .cli import AnomalibCLI
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\cli.py", line 19, in <module>
    from anomalib.cli.utils.help_formatter import CustomHelpFormatter, get_short_docstring
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\utils\__init__.py", line 6, in <module>
    from .help_formatter import CustomHelpFormatter
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\cli\utils\help_formatter.py", line 26, in <module>
    from anomalib.engine import Engine
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\engine\__init__.py", line 6, in <module>
    from .engine import Engine
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\engine\engine.py", line 20, in <module>
    from anomalib.callbacks.checkpoint import ModelCheckpoint
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\callbacks\__init__.py", line 18, in <module>
    from .model_loader import LoadModelCallback
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\callbacks\model_loader.py", line 12, in <module>
    from anomalib.models.components import AnomalyModule
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\__init__.py", line 13, in <module>
    from anomalib.models.components import AnomalyModule
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\__init__.py", line 8, in <module>
    from .feature_extractors import TimmFeatureExtractor, TorchFXFeatureExtractor
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\feature_extractors\__init__.py", line 6, in <module>
    from .timm import TimmFeatureExtractor
  File "C:\Users\shan\.conda\envs\anamolib\Lib\site-packages\anomalib\models\components\feature_extractors\timm.py", line 12, in <module>
    import timm
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "C:\Users\shan\AppData\Roaming\Python\Python311\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shan\.conda\envs\anamolib\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gowthamddy** [comment]
instead try this command --   pip install anomalib

**Comment by shanmugamani1023** [comment]
> instead try this command -- pip install anomalib

i tried that too,but its not work
