### ISSUE TITLE
[Bug]: InputNormalizationMethod missing

### ISSUE THREAD

**Issue by cile98** [open-edge-platform/anomalib#2451]
### Describe the bug

In the docs (https://anomalib.readthedocs.io/en/latest/markdown/guides/reference/data/image/folder.html) it shown that `InputNormalizationMethod` should be used with `Folder` class, but his enum doesn't exist anymore.

### Dataset

N/A

### Model

N/A

### Steps to reproduce the behavior

```
from anomalib.data.utils import InputNormalizationMethod

print(InputNormalizationMethod.NONE)
```

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

If `InputNormalizationMethod` is deprecated I suggest updating documentation and also `Folder` class annotation to reflect that.

### Pip/GitHub

pip

### Configuration YAML

```yaml
not relevant
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dev/oc_ml/oc_alien_detection/training_pipeline/training_pipeline/train.py", line 3, in <module>
    from anomalib.data.utils import InputNormalizationMethod
ImportError: cannot import name 'InputNormalizationMethod' from 'anomalib.data.utils' (/home/dev/oc_ml/oc_alien_detection/training_pipeline/.venv/lib/python3.10/site-packages/anomalib/data/utils/__init__.py)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhanghw19770217** [comment]
same problem to me. anyone can help us?

**Comment by samet-akcay** [comment]
@zhanghw19770217 @cile98 Apologies, this is left over from previous versions. It is not needed and unavailable in v1+.
I will add doctests to ensure this won't happen again

**Comment by rajeshgangireddy** [comment]
Looks like the documentation is updated. And there is no trace of `InputNormalizationMethod`. 
Closing.
